#ID array position in nota_credito
pos_ID = 0
#tipo_factura_nota array position in nota_credito
pos_tipo_factura_nota = pos_ID + 1
#Nombre_y_Apellido_Cliente array position in nota_credito
pos_Nombre_y_Apellido_Cliente = pos_tipo_factura_nota + 1
#tipo_documento array position in nota_credito
pos_tipo_documento = pos_Nombre_y_Apellido_Cliente + 1
#numero_documento_cliente array position in nota_credito
pos_numero_documento_cliente = pos_tipo_documento + 1
#condicion_venta_cliente array position in nota_credito
pos_condicion_venta_cliente = pos_numero_documento_cliente + 1
#condicion_iva_cliente array position in nota_credito
pos_condicion_iva_cliente = pos_condicion_venta_cliente + 1
#concepto array position in nota_credito
pos_concepto = pos_condicion_iva_cliente + 1
#fecha_servicio_desde array position in nota_credito
pos_fecha_servicio_desde = pos_concepto + 1
#fecha_servicio_hasta array position in nota_credito
pos_fecha_servicio_hasta = pos_fecha_servicio_desde + 1
#fecha_vencimiento_pago array position in nota_credito
pos_fecha_vencimiento_pago = pos_fecha_servicio_hasta + 1
#producto_servicio array position in nota_credito
pos_producto_servicio = pos_fecha_vencimiento_pago + 1
#porcentaje_bonificado array position in nota_credito
pos_porcentaje_bonificado = pos_producto_servicio + 1
#cantidad array position in nota_credito
pos_cantidad = pos_porcentaje_bonificado + 1
#codigo_producto array position in nota_credito
pos_codigo_producto = pos_cantidad + 1
#descripcion array position in nota_credito
pos_descripcion = pos_codigo_producto + 1
#precio_unitario array position in nota_credito
pos_precio_unitario = pos_descripcion + 1
#impuesto_adicional array position in nota_credito
pos_impuesto_adicional = pos_precio_unitario + 1
#importe_bonificado array position in nota_credito
pos_importe_bonificado = pos_impuesto_adicional + 1
#subtotal array position in nota_credito
pos_subtotal = pos_importe_bonificado + 1
#importe_neto array position in nota_credito
pos_importe_neto = pos_subtotal + 1
#importe_total array position in nota_credito
pos_importe_total = pos_importe_neto + 1
#importe_tributo array position in nota_credito
pos_importe_tributo = pos_importe_total + 1
#descripcion_impuesto_adicional array position in nota_credito
pos_descripcion_impuesto_adicional = pos_importe_tributo + 1
#alicuota_impuesto_adicional array position in nota_credito
pos_alicuota_impuesto_adicional = pos_descripcion_impuesto_adicional + 1
#nombre_apellido_vendedor array position in nota_credito
pos_nombre_apellido_vendedor = pos_alicuota_impuesto_adicional + 1
#cuit_vendedor array position in nota_credito
pos_cuit_vendedor = pos_nombre_apellido_vendedor + 1
#nombre_empresa array position in nota_credito
pos_nombre_empresa = pos_cuit_vendedor + 1
#punto_venta array position in nota_credito
pos_punto_venta = pos_nombre_empresa + 1
#razon_social array position in nota_credito
pos_razon_social = pos_punto_venta + 1
#domicilio array position in nota_credito
pos_domicilio = pos_razon_social + 1
#condicion_frente_iva array position in nota_credito
pos_condicion_frente_iva = pos_domicilio + 1
#ingresos_brutos array position in nota_credito
pos_ingresos_brutos = pos_condicion_frente_iva + 1
#fecha_inicio array position in nota_credito
pos_fecha_inicio = pos_ingresos_brutos + 1
#impuesto_adicional_global array position in nota_credito
pos_impuesto_adicional_global = pos_fecha_inicio + 1
#descripcion_impuesto_adicional_global array position in nota_credito
pos_descripcion_impuesto_adicional_global = pos_impuesto_adicional_global + 1
#alicuota array position in nota_credito
pos_alicuota_global = pos_descripcion_impuesto_adicional_global + 1
#cae_numero array position in nota_credito
pos_cae_numero = pos_alicuota_global + 1
#cae_fecha_vencimiento array position in nota_credito
pos_cae_fecha_vencimiento = pos_cae_numero + 1
#numero_comprobante array position in nota_credito
pos_numero_comprobante = pos_cae_fecha_vencimiento + 1